name: marker
base: core22
adopt-info: marker
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
      bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

slots:
  marker:
    interface: dbus
    bus: session
    name: com.github.fabiocolacio.marker

apps:
  marker:
    command: usr/bin/marker
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - network
      - network-status
      - network-bind
      - optical-drive
      - removable-media
    common-id: com.github.fabiocolacio.marker
    desktop: usr/share/applications/com.github.fabiocolacio.marker.desktop
        
parts:
  marker:
    source: https://github.com/fabiocolacio/Marker.git
    source-tag: 2020.04.04.2
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.fabiocolacio.marker.appdata.xml]
    meson-parameters:
      - --prefix=/snap/marker/current/usr
    build-snaps:
      - cmake
    build-packages:
      - libghc-pandoc-dev
      - libgtksourceview-3.0-dev
      - libgtkspell3-3-dev
    override-pull: |
      craftctl default
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    stage-packages:
      - libgtkspell3-3-0
    organize:
      snap/marker/current/usr: usr  
    
